name: shopmind
description: A smart offline intention-based shopping companion app with multi-user and PIN protection.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1
  uuid: ^3.0.7
  fl_chart: ^0.63.0
  lottie: ^2.4.0
  flutter_secure_storage: ^8.0.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
